name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Build project
      run: |
        echo "Building FietsRouteMee..."
        xcodebuild -project FietsRouteMee.xcodeproj \
          -scheme FietsRouteMee \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -configuration Debug \
          build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
        echo "Build completed successfully"
    
    - name: Skip tests (no test targets)
      run: |
        echo "Skipping tests - no test targets defined in project"
        echo "This is normal for a SwiftUI app without unit tests"
    
    - name: Check code style
      run: |
        # Add SwiftLint or other code style checks here
        echo "Code style check placeholder"
    
    - name: Security scan
      run: |
        # Add security scanning tools here
        echo "Security scan placeholder"
